"""Ajout de l'utilisateur admin

Revision ID: 750790420b73
Revises: 
Create Date: 2023-12-07 00:05:27.152468

"""
from alembic import op
import sqlalchemy as sa
from passlib.hash import sha256_crypt

# revision identifiers, used by Alembic.
revision = '750790420b73'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Insérez l'utilisateur admin
    op.execute("INSERT INTO user (username, password) VALUES ('admin', '" + sha256_crypt.hash("Aucune_idee!") + "')")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
